### ISSUE TITLE
remove 0.0.0.0 lcs-cops.adobe.io

### ISSUE THREAD

**Issue by StrongTequila** [ignaciocastro/adobe-is-dumb#1]
it's crush indesign after launch

**Comment by ignaciocastro** [comment]
**Not done.** Tried InDesign 18.5.1 with hosts file enabled, app did not crash and didn't do more than one request to lcs-cops. I'd recommend checking your activation solution, reinstalling or prefering an older version.
![image](https://github.com/ignaciocastro/adobe-is-dumb/assets/7141944/aa34e6a5-3b09-4259-a118-82a535014235)

**Comment by StrongTequila** [comment]
19.0.0.151 (2024) mac version, connected to demo account (no trial activation)
Sice patch version
closes immediately after loading when this particular address is blocked

**Comment by ignaciocastro** [comment]
> closes immediately after loading when this particular address is blocked

**Not done.** If you're 100% sure this address is what's causing the crash then you can use the list and remove the address yourself. lcs-cops is a known license check server and removing it to make one specific app version work will make the rest get unlicensed.

**Comment by StrongTequila** [comment]
100%, crashes with this address blocked, works fine without it, no windows about unlicensed software appear
The same problem occurs for other users of the Mac version, I have many client computers to check

**Comment by ignaciocastro** [comment]
> I have many client computers to check

This is _outside_ of my scope. This was created as a personal solution that I made public, not as a way for people to use it in enterprise settings. Adobe offers that service, not me.

If you're using this with mutliple computers then you can always host the list yourself without said address.

Issue closed and locked.
