### ISSUE TITLE
start and end markers removed from list.txt

### ISSUE THREAD

**Issue by LagunaJim** [ignaciocastro/adobe-is-dumb#11]
Hi.  Was it intentional to remove the markers ### START... and ### END... from list.txt ?

**Comment by ignaciocastro** [comment]
I have no clue what you're talking about. All lists have followed the same format ever since it's first itineration back in October. Check commit a4d7ef19a69adfab45e552859261e76ea2014d93

**Comment by LagunaJim** [comment]
Sorry - someone else was taking your file and writing start and end markers to it before implementing -- apologies for the confusion.
