### ISSUE TITLE
adobe-is-dumb breaks Revealing function in Lightroom Classic

### ISSUE THREAD

**Issue by madman80** [ignaciocastro/adobe-is-dumb#4]
The list includes lcs-cops.adobe.io that is necessary for LRC to work. Revealing module needs an internet connection to this adress.
Maybe you need to remove this line of your list. Passed the 14 test days I'm not sure if lcs-cops.adobe.io can check your license and disabling cracked license.

**Comment by ignaciocastro** [comment]
**Done ✅** lcs-cops domains have been commented out, and are due to be completely removed if no issue relating to them is reported again. Thank you!
