### ISSUE TITLE
Adobe Genuine Warning is back.

### ISSUE THREAD

**Issue by CapacR** [ignaciocastro/adobe-is-dumb#6]
Hi,
First of all, let me thank you for your work, it's a very well done job !
I'm currently using your ADList for PiHole, but since a few days, I get the Adobe Genuine Warning again with my AdobeApps.
I tried to use your host file as well, but unfortunately without success.
Could you help ?

**Comment by ignaciocastro** [comment]
**❔ Question** @CapacR, Thank you for your comments. Adobe has started to use multiple domains to achieve the popup window, this is seen happening more often on 2024 versions.
 1. Could you check whether you have the latest version of the blocklist?
 2. Could you install Fiddler Classic and check which domain is running the "integritychecker" url once the popup appears?
 3. Lastly, as a temp fix, could you add the wildcard "*.adobestats.io" to your PiHole blocklist and check one more time ? This is a benefit that works for Pi Hole users and I've been considering whether to apply it to the new set of domains.

**Comment by ignaciocastro** [comment]
**❌ Closed after 5 days of inacticity.**
