### ISSUE TITLE
[FR] Generate a hosts.txt w/o the header

### ISSUE THREAD

**Issue by vavavr00m** [ignaciocastro/adobe-is-dumb#7]
with the loopback address:
```
0.0.0.0 ic.adobe.io
0.0.0.0 cc-api-data.adobe.io
0.0.0.0 dyzt55url8.adobe.io
```

domains only:
```
ic.adobe.io
cc-api-data.adobe.io
dyzt55url8.adobe.io
```

single line, delimited by a space, domains only
```
ic.adobe.io cc-api-data.adobe.io dyzt55url8.adobe.io
```

**Comment by ignaciocastro** [comment]
**💬 More feedback needed** The idea of the header is to be able to differentiate between your original hosts file and this blocklist, considering the standard user might have more hosts to block (or more hosts lists) than this one.
While as of now this will be left as "**not planned**", I'd appreciate if more users gave feedback whether they think this would be useful. If more people are interested in clean lists with no header text, then I'll create them.
Thank you for your comment!
